# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  push:
  pull_request:

concurrency:
  group: compile-${{ github.workflow }}-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
  cancel-in-progress: true

jobs:
  validate:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16']
    name: Lint test on Node ${{ matrix.node }}
    steps:
      - run: echo ${{github.ref}}

      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          always-auth: 'true'
          registry-url: 'https://nexus.tools.services.qld.gov.au/nexus/repository/npm_all/'

      - name: npmrc #run on lint step (Which is cached)
        run: |
          npm -v
          node -v
          cat /home/runner/work/_temp/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NEXUSREADONLY2NPMTOKEN }}

      - name: Install
        run: | # Install packages
         npm install --prefer-offline --no-audit --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NEXUSREADONLY2NPMTOKEN }}

      # `npm rebuild` will run all those post-install scripts for us.
      - name: rebuild and prepare
        run: npm rebuild && npm run prepare --if-present

      - name: Lint
        run: |
          npm run lint

  build:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    name: Build and Deploy on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          always-auth: 'true'
          registry-url: 'https://nexus.tools.services.qld.gov.au/nexus/repository/npm_all/'
      - name: Install #run on lint step (Which is cached)
        run: | # Install packages
          npm install --prefer-offline --no-audit --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NEXUSREADONLY2NPMTOKEN }}

      # `npm rebuild` will run all those post-install scripts for us.
      - name: rebuild and prepare
        run: npm rebuild && npm run prepare --if-present

      - name: Build 🔧
        run: | # build the files
          npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: ./dist

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: display branch name
        shell: bash
        run: echo "${{ steps.extract_branch.outputs.branch }}"

      - name: setup Publish
        run: |
          set -x
          cp -r ./binary-repo/* ./dist

      - name: Publish
        uses: qld-gov-au/gha-publish-to-git@master
        with:
          repository: ${{ secrets.TARGET_REPO }}
          git_ref: '${{ github.ref }}'
          branch: '${{ steps.extract_branch.outputs.branch }}'
          github_token: '${{ secrets.GH_TOKEN }}'
          github_pat: '${{ secrets.GH_PAT }}'
          source_folder: dist
          tag_branch: main
        if: success()

